Repository ClickHouse/clickhouse-go, pull requests merged in 2022-11, with the labels that each got.

#802 Support inserting Enums as int8/int16/int values
  lib/column/enum16.go
  lib/column/enum8.go
  tests/std/enum_test.go
Labels: enhancement

#811 Allow optional HTTP headers; For HTTPS connections, pass auth as headers
  clickhouse_options.go
  conn_http.go
  conn_http_query.go
Labels: bug, enhancement

#821 Issue 816 - support for nullable tuples
  .github/workflows/run-tests.yml
  lib/column/tuple.go
  tests/issues/816_test.go
Labels: bug

#829 allow for escaped columns
  conn_batch.go
  tests/issues/828_test.go
Labels: bug
