Repository ClickHouse/clickhouse-go, pull requests merged in 2022-09, with the labels that each got.

#735 Fix error in nil check for *Decimal column Append
  lib/column/decimal.go
  tests/columnar_batch_test.go
Labels: bug

#740 Add cloud int tests
  .github/workflows/run-tests.yml
  Makefile
  tests/abort_test.go
  tests/base_types_test.go
  tests/bigint_test.go
  tests/bool_test.go
  tests/columnar_batch_test.go
  tests/compression_test.go
  tests/conn_test.go
  tests/date32_test.go
  tests/date_test.go
  tests/datetime64_test.go
  tests/datetime_test.go
  tests/ddl_test.go
  tests/decimal_test.go
  tests/enum_test.go
  tests/fixed_string_test.go
  tests/float_test.go
  tests/flush_test.go
  tests/geo_multipolygon_test.go
  tests/geo_point_test.go
  tests/geo_polygon_test.go
  tests/geo_ring_test.go
  tests/issues/209/main.go
  tests/issues/360/main.go
  tests/issues/389_test.go
  tests/issues/406_test.go
  tests/issues/412_test.go
  tests/issues/470/main.go
  tests/issues/484/main.go
  tests/issues/485/main.go
  tests/issues/546_test.go
  tests/issues/548_test.go
  tests/issues/570_test.go
  tests/issues/615_test.go
  tests/issues/647_test.go
  tests/json_test.go
  tests/lowcardinality_test.go
  tests/map_test.go
  tests/nested_test.go
  tests/nullable_array_test.go
  tests/simple_aggregate_function_test.go
  tests/std/close_test.go
  tests/std/conn_test.go
  tests/std/connect_check_test.go
  tests/std/string_test.go
  tests/std/temporary_table_test.go
  tests/std/utils.go
  tests/std/uuid_test.go
  tests/stress/stress.go
  tests/string_test.go
  tests/tuple_test.go
  tests/utils.go
  tests/uuid_test.go
Labels: enhancement

#766 Align timezone handling with spec
  .github/workflows/run-tests.yml
  bind.go
  clickhouse.go
  lib/column/date.go
  lib/column/date32.go
  lib/column/datetime.go
  lib/column/datetime64.go
  tests/date32_test.go
  tests/date_test.go
  tests/datetime64_test.go
  tests/datetime_test.go
  tests/issues/759_test.go
  tests/resources/custom.xml
  tests/utils.go
Labels: bug, enhancement

#767 support custom datetime in scan
  lib/column/date.go
  lib/column/date32.go
  lib/column/datetime.go
  lib/column/datetime64.go
  lib/column/uuid.go
  tests/date32_test.go
  tests/date_test.go
  tests/datetime64_test.go
  tests/datetime_test.go
Labels: enhancement

#768 Pass nil for LowCardinality(Nullable(X))
  lib/column/lowcardinality.go
  tests/issues/504_test.go
  tests/issues/506_test.go
  tests/issues/517_test.go
  tests/issues/546_test.go
  tests/issues/548_test.go
  tests/issues/570_test.go
  tests/issues/578_test.go
  tests/issues/584_test.go
  tests/issues/592_test.go
  tests/issues/615_test.go
  tests/issues/647_test.go
  tests/issues/648_test.go
  tests/issues/692_test.go
  tests/issues/693_test.go
  tests/issues/751_test.go
Labels: bug

#771 sequential inserts and timeouts
  .github/workflows/run-tests.yml
  tests/ddl_test.go
  tests/issues/546_test.go
  tests/issues/548_test.go
  tests/std/utils.go
  tests/utils.go
Labels: enhancement
