Repository ClickHouse/clickhouse-go, pull requests merged in 2023-05, with the labels that each got.

#987 Pass http.ProxyFromEnvironment configuration to http.Transport
  conn_http.go
  tests/std/conn_test.go
  tests/utils.go
Labels: release-candidate, fix, Semver-Patch

#991 support http connection reuse after external table query execution
  conn_http.go
  tests/issues/990_test.go
Labels: release-candidate, fix

#993 Custom settings support in native protocol
  conn.go
  conn_http.go
  context.go
  lib/proto/query.go
  tests/conn_test.go
  tests/resources/custom.xml
  tests/std/conn_test.go
Labels: release-candidate, fix, Semver-Patch

#971 Tuple scan respects both value and pointer variable
  lib/column/tuple.go
  tests/issues/762_test.go
  tests/std/tuples_test.go
Labels: fix

#996 Support [16]byte/[]byte typed scan/append for IPv6 column
  lib/column/ipv6.go
  tests/ipv6_test.go
Labels: enhancement, release-candidate

#999 Auto close idle connections in native protocol in respect of ConnMaxLifetime option
  clickhouse.go
  tests/client_info_test.go
  tests/conn_test.go
  tests/issues/957_test.go
  tests/query_parameters_test.go
  tests/read_only_user_test.go
  tests/utils.go
Labels: release-candidate, fix

#998 Add custom dialer option to http based conn
  conn_http.go
  tests/custom_dial_test.go
Labels: enhancement, release-candidate
