Repository ClickHouse/clickhouse-go, pull requests merged in 2023-12, with the labels that each got.

#1144 Add sql.Valuer support for all types
  contributors/list
  lib/column/array.go
  lib/column/array_gen.go
  lib/column/bigint.go
  lib/column/bool.go
  lib/column/codegen/array.tpl
  lib/column/codegen/column.tpl
  lib/column/column_gen.go
  lib/column/date.go
  lib/column/date32.go
  lib/column/datetime.go
  lib/column/datetime64.go
  lib/column/decimal.go
  lib/column/enum16.go
  lib/column/enum8.go
  lib/column/fixed_string.go
  lib/column/geo_multi_polygon.go
  lib/column/geo_point.go
  lib/column/geo_polygon.go
  lib/column/geo_ring.go
  lib/column/ipv4.go
  lib/column/ipv6.go
  lib/column/map.go
  lib/column/string.go
  lib/column/tuple.go
  lib/column/uuid.go
  tests/array_test.go
  tests/bigint_test.go
  tests/bool_test.go
  tests/date32_test.go
  tests/date_test.go
  tests/datetime64_test.go
  tests/datetime_test.go
  tests/decimal_test.go
  tests/enum_test.go
  tests/fixed_string_test.go
  tests/float64_test.go
  tests/geo_multipolygon_test.go
  tests/geo_point_test.go
  tests/geo_polygon_test.go
  tests/geo_ring_test.go
  tests/ipv4_test.go
  tests/ipv6_test.go
  tests/map_test.go
  tests/string_test.go
  tests/tuple_test.go
  tests/uuid_test.go
Labels: enhancement

#1152 Iterable ordered map alternative with improved performance
  bind.go
  examples/clickhouse_api/main_test.go
  examples/clickhouse_api/map.go
  lib/column/map.go
  tests/map_test.go
Labels: enhancement, performance

#1160 Update README - mention HTTP protocol usable only with `database/sql` interface
  README.md
Labels: bug, fix

#1156 Support bool alias type
  lib/column/bool.go
  tests/bool_test.go
Labels: enhancement

#1153 Fix README example for Debugf
  README.md
Labels: bug, fix

#1168 fix panic in contextWatchDog nil pointer check
  conn_batch.go
Labels: bug, fix
