Repository ClickHouse/clickhouse-go, pull requests merged in 2023-09, with the labels that each got.

#1083 Fix escaping double quote in SQL statement in prepare batch
  conn_batch.go
  tests/issues/1049_test.go
Labels: bug, fix

#1092 Improving object allocation for (positional) parameter binding
  bind.go
Labels: release-candidate

#1080 chore: unnecessary use of fmt.Sprintf
  clickhouse_std.go
Labels: release-candidate

#1084 parseDSN: support connection pool settings (#1082)
  clickhouse_options.go
  clickhouse_options_test.go
Labels: enhancement, release-candidate
