Repository ClickHouse/clickhouse-go, pull requests merged in 2023-08, with the labels that each got.

#1051 Support scan from uint8 to bool
  lib/column/codegen/column.tpl
  lib/column/column_gen.go
  tests/uint8_test.go
Labels: enhancement, release-candidate

#1052 Binding arguments for AsyncInsert interface
  bind.go
  bind_test.go
  clickhouse.go
  clickhouse_std.go
  conn_async_insert.go
  conn_http_async_insert.go
  examples/clickhouse_api/async.go
  examples/std/async.go
  lib/driver/driver.go
Labels: release-candidate

#1063 Batch rows count API
  conn_batch.go
  conn_http_batch.go
  lib/driver/driver.go
  tests/array_test.go
  tests/base_types_test.go
  tests/bigint_test.go
  tests/bool_test.go
  tests/columnar_batch_test.go
  tests/date32_test.go
  tests/datetime_test.go
  tests/decimal_test.go
  tests/empty_query_test.go
  tests/enum_test.go
  tests/fixed_string_test.go
  tests/float_test.go
  tests/geo_multipolygon_test.go
  tests/geo_polygon_test.go
  tests/geo_ring_test.go
  tests/ipv4_test.go
  tests/map_test.go
  tests/nested_test.go
  tests/nullable_array_test.go
  tests/simple_aggregate_function_test.go
  tests/string_test.go
  tests/struct_map_test.go
  tests/tuple_test.go
  tests/uuid_test.go
Labels: enhancement, release-candidate

#1062 Implement release connection in batch
  README.md
  clickhouse.go
  clickhouse_std.go
  conn_batch.go
  conn_http_batch.go
  examples/clickhouse_api/batch_release_connection.go
  examples/clickhouse_api/main_test.go
  lib/driver/driver.go
  lib/driver/options.go
  tests/batch_release_connection_test.go
  tests/utils.go
Labels: enhancement, release-candidate

#1069 fix: native format Date32 representation
  go.mod
  go.sum
  tests/issues/1066_test.go
  tests/issues/1067_test.go
Labels: fix

#1071 fix: update ch-go to remove string length limit
  go.mod
  go.sum
Labels: bug, fix
