Repository ClickHouse/clickhouse-go, pull requests merged in 2023-07, with the labels that each got.

#941 Retry for batch API
  clickhouse.go
  clickhouse_std.go
  conn_batch.go
  conn_http_batch.go
  tests/issues/798_test.go
Labels: release-candidate

#1029 Fix netip.Addr pointer panic
  lib/column/ipv4.go
  lib/column/ipv6.go
  tests/ipv4_test.go
Labels: bug, fix

#1032 Remove incompatible server version direct stdout
  conn.go
  conn_http.go
Labels: bug, fix

#1039 Implement elapsed time in query progress
  lib/proto/const.go
  lib/proto/progress.go
Labels: enhancement, release-candidate

#1042 Release connection slot on connection acquire timeout
  clickhouse.go
Labels: bug, release-candidate, fix

#1044 Fix InsertAsync typo in docs
  README.md
Labels: docs, fix
