Repository ClickHouse/clickhouse-go, pull requests merged in 2023-10, with the labels that each got.

#1085 Remove dependency on github.com/satori/go.uuid
  go.mod
  go.sum
  tests/uuid_test.go
Labels: release-candidate

#1116 Fix insertion of empty map into JSON column by using _dummy subcolumn
  lib/column/json.go
  tests/issues/1113_test.go
Labels: bug, fix

#1118 Fix panic on zero/nil value for net.IP for IPv4 and IPv6 types
  lib/column/ipv4.go
  lib/column/ipv6.go
  tests/issues/1106_test.go
Labels: bug, fix

#1126 drop unnecessary bytes to str conversion
  lib/column/string.go
Labels: enhancement, performance

#1130 reflection-free AppendRow for plain arrays
  lib/column/array.go
  lib/column/array_gen.go
  lib/column/codegen/array.tpl
  lib/column/codegen/main.go
Labels: enhancement

#1129 Support scan of custom types implementing sql.Scanner into array/tuple columns
  lib/column/tuple.go
  tests/issues/1128_test.go
Labels: enhancement

#1036 Cleanup examples/std/compression.go
  examples/std/compression.go
Labels: stale
