Repository ClickHouse/clickhouse-go, pull requests merged in 2023-04, with the labels that each got.

#946 Support driver.Valuer in String and FixedString columns
  lib/column/fixed_string.go
  lib/column/string.go
  tests/fixed_string_test.go
  tests/string_test.go
Labels: release-candidate

#963 Support boolean and pointer type parameter binding
  bind.go
  bind_test.go
Labels: release-candidate

#964 Reset the pointer to the nullable field
  lib/column/nullable.go
  tests/issues/955_test.go
Labels: release-candidate, fix

#965 Enable to use ternary operator with named arguments
  bind.go
  bind_test.go
Labels: release-candidate, fix

#975 Do not return hard error on unparsable version in HTTP proto
  conn_http.go
  lib/proto/handshake.go
Labels: enhancement, release-candidate
