Repository ClickHouse/clickhouse-go, pull requests merged in 2023-03, with the labels that each got.

#924 fix: fix connect.compression's format verb
  conn.go
Labels: bug

#936 fix: small typo in the text of an error
  lib/proto/block.go
Labels: release-candidate

#926 Allow `Auth.Database` option to be empty
  clickhouse_options.go
  clickhouse_options_test.go
  tests/conn_test.go
  tests/std/conn_test.go
Labels: release-candidate

#938 Support customized "url path" in http connection
  clickhouse_options.go
  conn_http.go
  tests/resources/nginx.conf
  tests/std/conn_test.go
  tests/utils.go
Labels: enhancement, release-candidate
