Repository ClickHouse/clickhouse-go, pull requests merged in 2024-08, with the labels that each got.

#1373 Fix column list parsing for multiline INSERT statements
  batch.go
  batch_test.go
Labels: bug, fix

#1374 Optimize Date/Date32 scan
  lib/column/date.go
  lib/column/date32.go
  lib/column/datetime.go
  lib/column/datetime64.go
  lib/column/time_helper.go
  lib/column/time_helper_test.go
Labels: enhancement, performance

#1385 ClickHouse 24.8
  .github/workflows/run-tests-cloud.yml
  .github/workflows/run-tests-head.yml
  .github/workflows/run-tests.yml
Labels: tests:run-cloud, tests:run-head

#1396 Validate connection in bad state before query execution in the stdlib database/sql driver
  clickhouse_std.go
  tests/issues/1395_test.go
Labels: bug, fix
