Repository ClickHouse/clickhouse-go, pull requests merged in 2024-03, with the labels that each got.

#1218 Fix Date32 extremes values handling
  lib/column/date32.go
  tests/date32_test.go
Labels: bug, fix

#1217 Fix column with double quotes PrepareBatch failed.(#1216)
  conn_batch.go
  tests/issues/1216_test.go
Labels: bug, fix

#1213 Stream HTTP response body read for decompression
  clickhouse_rows.go
  conn_http.go
  conn_http_query.go
Labels: enhancement, Semver-Minor

#1228 Adds the ability to Append a zero valued time.Time
  go.mod
  go.sum
  lib/column/date_helpers.go
  lib/column/date_helpers_test.go
  tests/std/date32_test.go
  tests/std/date_test.go
  tests/std/datetime64_test.go
  tests/std/datetime_test.go
Labels: bug, fix

#1214 Ignore materialized and alias cols infered during HTTP prepare batch
  conn_http_batch.go
  tests/std/materialized_column_test.go
Labels: bug, fix

#1233 Experimental streaming SELECT results into batch insert
  conn_batch.go
  tests/batch_block_test.go
Labels: enhancement, experimental

#1249 Fix panic on tuple scan on []any
  lib/column/tuple.go
  tests/issues/1245_test.go
  tests/utils.go
Labels: bug, fix, tests:run-cloud

#1251 Fix TestBatchAppendRows work different on cloud
  tests/batch_block_test.go
Labels: tests:run-cloud

#1256 Align error message assertion to new missing custom setting error formatting
  tests/conn_test.go
  tests/std/conn_test.go
Labels: tests:run-head

#1258 CI chores
  .github/workflows/run-tests.yml
  examples/std/main_test.go
  examples/std/session.go
  tests/resources/custom.xml
  tests/utils.go
Labels: tests:run-cloud, tests:run-head

#1260 Zero-value timestamp to be formatted as toDateTime(0) in bind
  bind.go
  bind_test.go
  tests/issues/1016_test.go
Labels: tests:run-cloud, tests:run-head
