Repository ClickHouse/clickhouse-go, pull requests merged in 2024-05, with the labels that each got.

#1286 Always compress responses when the client compression is on
  conn_http.go
  conn_http_batch.go
Labels: enhancement

#1276 Optional flag to close query with flush
  conn_batch.go
  lib/driver/options.go
  tests/issues/1271_test.go
Labels: enhancement

#1283 Fix nil checks when appending slices of pointers
  lib/column/bigint.go
  lib/column/codegen/column.tpl
  lib/column/column_gen.go
  lib/column/datetime.go
  lib/column/datetime64.go
  lib/column/geo_multi_polygon.go
  lib/column/geo_point.go
  lib/column/geo_polygon.go
  lib/column/geo_ring.go
  lib/column/ipv4.go
Labels: fix

#1305 Use Go 1.22 in head tests
  .github/workflows/run-tests-head.yml
Labels: tests:run-head
